version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_ROOT_HOST: '%'
    volumes:
    # /db/init.sql → File SQL trên máy host (local).
    # /docker-entrypoint-initdb.d/init.sql → Thư mục đặc biệt trong container PostgreSQL Khi container PostgreSQL khởi động, nó sẽ chạy tất cả các file .sql trong thư mục này để khởi tạo database.
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  # golang:
  #   image: golang:1.23
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - .:/go/src/mvc_golang
  #   working_dir: /go/src/mvc_golang
  #   command: bash -c "export GO111MODULE=on && go mod tidy && go mod vendor && go install github.com/swaggo/swag/cmd/swag@latest && go install github.com/mitranim/gow@latest && swag init && gow run ."
  #   depends_on:
  #     - db